### ISSUE TITLE
New Members

### ISSUE THREAD

**Issue by veritaci** [ritokatsuga/better-nijisort#2]
Hi, this is not really an issue but would just love to ask if you could also add the new members from Nijisanji JP "Dytica" namely Murakumo Kagetsu, Inami Rai, Hoshirube Sho, Koyanagi Rou. That's all, sorry for bothering you and thank you for making this sorter.

**Comment by ufalsalman** [comment]
Thank you for your feedback. I haven't caught up with recent male livers lately, but I already pushed the entry for the new livers.

**Comment by veritaci** [comment]
Thanks heaps, mate! <3
